#+title: Kiran's Art work
#+NAV_SECTIONS: [[file:index.org][About Me]] [[file:index.org::*Publications][Publications]] [[file:art.org][Artwork]] [[file:posts.org][Posts]]
#+NAV_SECTION: Artwork
#+HIDDEN: true

* Kiran's Artwork
:PROPERTIES:
:subtitle: A few scribbles I've done over time~
:END:

I like to draw a lot as a hobby in my free time; I find it very
relaxing, and I love the way that it allows to capture aspects of my
lived experiences, both as a minority and as a trans woman. Sometimes
this may come off a bit cringe, but I enjoy it nonetheless.

My art skills are definitely still a work in progress, but I hope you
enjoy the following gallery regardless:

@@html: <div class="artwork-grid">@@
#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lmvnkznh222a" data-bluesky-cid="bafyreihb7pqa4vz7b6ubobnpprirkjfxhqpbfa75fvxo5ssefjixxze5xy" data-bluesky-embed-color-mode="system"><p lang="en">Today&#x27;s daily Femme Columbo sketches~

#drawing #art #sketch #columbo #pencil<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmvnkznh222a?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmvnkznh222a?ref_src=embed">15 April 2025 at 22:28</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lmqk6y6eos2p" data-bluesky-cid="bafyreicqz7ye2q2cmh65ha7fx63bu53macsztz5qrjezk6bep5yfwjh644" data-bluesky-embed-color-mode="system"><p lang="en">Another columbo sketch #drawing #columbo #art #pencil #traditionalArt<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmqk6y6eos2p?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmqk6y6eos2p?ref_src=embed">13 April 2025 at 21:45</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lmeennyazk2c" data-bluesky-cid="bafyreig63foh7ogz4jl5rcjkhr3dyf6miopoyyp5n4cw4lciz2umdn5ceu" data-bluesky-embed-color-mode="system"><p lang="en">and one more willxsion #wistoria #yaoi fanart haha watching this show I could not help but think how every other character ship in this show was completely blown out of the water by these two<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmeennyazk2c?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmeennyazk2c?ref_src=embed">9 April 2025 at 01:33</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lmeeffzh6c2c" data-bluesky-cid="bafyreidrcub6n2ijvx5sgtvas73ovhfxxxezzg6lgtmf3zcgsrjzrgh77i" data-bluesky-embed-color-mode="system"><p lang="en">Sorry Elfaria, Will&#x27;s heart already belongs to another~

In other words, enjoying the #Wistoria anime; best girl is Sion, I refuse to hear any other words. Glad to see some good #tsundere representation for once~

#willxsion #anime #manga #WandAndSword #Fanart #yaoi<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmeeffzh6c2c?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmeeffzh6c2c?ref_src=embed">9 April 2025 at 01:29</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lmbowtk5f22g" data-bluesky-cid="bafyreiacwpsl5x6lacubgnad2aocqlpvqots7vd7quphjtpf7zxysvjgiu" data-bluesky-embed-color-mode="system"><p lang="en">One sec~ Femme Columbo #art #sketch #drawing #pencilSketch #traditionalArt #columbo<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmbowtk5f22g?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lmbowtk5f22g?ref_src=embed">8 April 2025 at 00:00</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lm3wvutjnk2p" data-bluesky-cid="bafyreiaffdvwiu55hz3h2wfxuwx2sgt53llbpyzy4z5ceq75lq4vxgtule" data-bluesky-embed-color-mode="system"><p lang="en">Devil may cry anime has a lot of uuuhh plot. I love it so far. 

Plot/10 would recommend.

#drawing #sketch #art #devilmaycry #dante #fanart  #pencilSketch #anime #manga<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lm3wvutjnk2p?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lm3wvutjnk2p?ref_src=embed">5 April 2025 at 17:06</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llzeh5mc322g" data-bluesky-cid="bafyreifg6fcow6a44skbgjf3xfx5l3w22yvolhewqgf6idepjpjtuylhvm" data-bluesky-embed-color-mode="system"><p lang="en">Not bad~ femme Columbo Daily Sketch #sketch #drawing #columbo #genderswap #art #pencil<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llzeh5mc322g?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llzeh5mc322g?ref_src=embed">4 April 2025 at 16:31</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llxvx3qhtc2f" data-bluesky-cid="bafyreifaysg7q7pci5ez76grsldvcehclep7ywo6moxi6cfhc5arheijja" data-bluesky-embed-color-mode="system"><p lang="en">a call for help and a comic about some thoughts I&#x27;ve been having recently

#comic #webcomic #queerArt #trans<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llxvx3qhtc2f?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llxvx3qhtc2f?ref_src=embed">4 April 2025 at 02:38</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llxkolivf22j" data-bluesky-cid="bafyreifag2btc7askaqk4y6vopdpt4ilojw2aaqedwrthj75i2cthwlnsy" data-bluesky-embed-color-mode="system"><p lang="en">Daily sketch for today~

#sketch #drawing #columbo #genderswap<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llxkolivf22j?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llxkolivf22j?ref_src=embed">3 April 2025 at 23:17</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llsdwtzswk27" data-bluesky-cid="bafyreidzcc4tf4xo4ds3bf7mbdq4cgsa3qttc2ff5tvsayiixxaerj4p6u" data-bluesky-embed-color-mode="system"><p lang="en">I&#x27;m just a lil gal - Femme Columbo

Daily sketch for today #sketch #drawing #art #Columbo<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llsdwtzswk27?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llsdwtzswk27?ref_src=embed">1 April 2025 at 21:33</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llpyf6g2e226" data-bluesky-cid="bafyreicurtz4vsugjhn2vi2pyncdole5miitvbjzxjgec5wdzio4i4ahxi" data-bluesky-embed-color-mode="system"><p lang="en">daily sketch for today #sketch #drawing #traditionalArt<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llpyf6g2e226?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llpyf6g2e226?ref_src=embed">31 March 2025 at 23:01</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llmv3a4gic24" data-bluesky-cid="bafyreifztfbvxl3m6nblpq4tq3hkbb5vikfsov5lz3t64iy6plxwif6qmm" data-bluesky-embed-color-mode="system"><p lang="en">I guess I never miss - Femme columbo 

Daily sketch #sketch #columbo<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llmv3a4gic24?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llmv3a4gic24?ref_src=embed">30 March 2025 at 17:23</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llhmygrtd226" data-bluesky-cid="bafyreid2zdtix37urciq6mh64p5452ysbkjjh6zl5qr5pqvkc6t6um7dqe" data-bluesky-embed-color-mode="system"><p lang="en">mfw most used language in a verification project is C<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llhmygrtd226?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llhmygrtd226?ref_src=embed">28 March 2025 at 15:15</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llfs72taqc2h" data-bluesky-cid="bafyreieprpiikjf3jpwqw4cm6cmbst7zajnnlw267vj27u7gxv5egvdar4" data-bluesky-embed-color-mode="system"><p lang="en">Femme-Columbo didn&#x27;t appreciate the Funko pop collection~

Daily sketch #sketch #columbo #drawing #pencilArt #Art<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llfs72taqc2h?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llfs72taqc2h?ref_src=embed">27 March 2025 at 21:43</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export


#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3llazhmwaok2r" data-bluesky-cid="bafyreicphaosvqy32b2hvmb22ygsjggc4ob2amuj5mq5sogo6q2k4tyqqq" data-bluesky-embed-color-mode="system"><p lang="en">Daily sketch #sketch #drawing #pencilArt #Columbo<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llazhmwaok2r?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3llazhmwaok2r?ref_src=embed">26 March 2025 at 00:10</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lkwjxwvt722e" data-bluesky-cid="bafyreiajg7jignxubrmyp2d5mgxcjvgym7ov2z4op4aljohsig2ivkbyya" data-bluesky-embed-color-mode="system"><p lang="en">Daily sketch~

#dailySketch #sketch #anime #manga #mangaArt #pencil #pencilSketch #art #drawing #queerArt #transArtist<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkwjxwvt722e?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkwjxwvt722e?ref_src=embed">21 March 2025 at 20:06</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lkujrc27b226" data-bluesky-cid="bafyreih6eiojn4vvqqs47veswvyyiyz6ze3ffytsx7efxqqbtcoqqukmdu" data-bluesky-embed-color-mode="system"><p lang="en">Not my best sketch but eeeh whatever

#sketch #pencilArt #drawing #art #queerArt #transArtist<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkujrc27b226?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkujrc27b226?ref_src=embed">21 March 2025 at 00:57</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lkrspnqmbc24" data-bluesky-cid="bafyreibjwgnsynyrkrmo4fpkweovas7bllfvn66xs6qhjps2ur6vo72w7a" data-bluesky-embed-color-mode="system"><p lang="en">Daily sketch~ #trans #art #queerArt #pencilSketch #drawing #dailySketch #anime #manga #sketch<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkrspnqmbc24?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkrspnqmbc24?ref_src=embed">19 March 2025 at 22:59</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lkhtso2p3c2z" data-bluesky-cid="bafyreidmlyhl6z4gd2le7rofv62bjdsh6tqcemgajippuvfic35zyqkqr4" data-bluesky-embed-color-mode="system"><p lang="en">tgirls in sports be like...

#trans #QueerArt #DigitalArt #Webcomic #Comic #transArtist #Drawing #MadeWithKrita #art<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkhtso2p3c2z?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkhtso2p3c2z?ref_src=embed">15 March 2025 at 23:52</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lkbml6jd2s22" data-bluesky-cid="bafyreifhe7of3xzj6xowl5hzmkor3lcqatuvty4terat7shhaenzhzkflq" data-bluesky-embed-color-mode="system"><p lang="en">Take a picture~ it&#x27;ll last longer!

#sketch #digitalArt #traditionalArt #madeWithKrita #transArtist #QueerArt #PencilDrawing #Drawing #manga #anime #AnimeArt<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkbml6jd2s22?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkbml6jd2s22?ref_src=embed">13 March 2025 at 12:27</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lkafrauwk22b" data-bluesky-cid="bafyreiays6jqzaprv44tt4c5xuflbxski4l6um24fa2r3jbxi4btufbfke" data-bluesky-embed-color-mode="system"><p lang="en">mfw when I date white guys~

#sketch #transArtist #pencil #digitalArt #madeWithKrita #traditionalArt #queerArt #pencilSketch #drawing #transArtist #trans #manga #anime<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkafrauwk22b?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lkafrauwk22b?ref_src=embed">13 March 2025 at 00:52</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lk6xmmq2gs2r" data-bluesky-cid="bafyreicjun4zgalfnkeguqckmqzafvemanb2mplo3ka2t35g534lkh6uny" data-bluesky-embed-color-mode="system"><p lang="en">Hmmmm~

#sketch #drawing #traditionalArt #queerArt #anime #Manga #transArtist
#pencilArt<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lk6xmmq2gs2r?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lk6xmmq2gs2r?ref_src=embed">12 March 2025 at 11:07</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lk4mnfgh7k2j" data-bluesky-cid="bafyreiec4egofnrzdhsejtfyj2qq4uj4woijwny6mgyiexzxybhkrb77vm" data-bluesky-embed-color-mode="system"><p lang="en">Geez senpai~ what do you want me to do exactly?

#sketch #anime #manga #queerArt #transArtist #Art #pencil<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lk4mnfgh7k2j?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lk4mnfgh7k2j?ref_src=embed">11 March 2025 at 12:45</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3ljyu6piux22y" data-bluesky-cid="bafyreielkpn76dnvcj3n67p4u7babc7drlgoftoh7wsgsaiij2oyitj3xi" data-bluesky-embed-color-mode="system"><p lang="en">Would you join me for a dance~

#sketch #selfie #art #traditionalArt #TransArtist #TransJoy #trans #anime #manga<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ljyu6piux22y?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ljyu6piux22y?ref_src=embed">10 March 2025 at 00:49</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3ljo7rhux2s24" data-bluesky-cid="bafyreidislsswtzvrmypxvj7duzwcckvtg4wfjvprhfp4ljvz6m2vchhvm"><p lang="en">Talking to my hair~

#traditionalArt #comic #webcomic #sliceoflife #comic #webtoon #DigitalArt<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ljo7rhux2s24?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ljo7rhux2s24?ref_src=embed">5 March 2025 at 18:17</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3ljmilhyk7k2z" data-bluesky-cid="bafyreicb63jdjc42ulmebksumrjpys53g5cswjvbimkfn3froi4nprfr6e"><p lang="en">My daily routine~ can anyone relate hehe :3 :3 :3

#Krita #Webcomic #QueerArt #TransArtist #DigitalArt #webcomics #Krita_artists #BskyArt  #comicart #illustration #Sketch #DailyLife #SliceOfLife<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ljmilhyk7k2z?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ljmilhyk7k2z?ref_src=embed">5 March 2025 at 01:50</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lio44ccbm22m" data-bluesky-cid="bafyreicbbbcqihqnp4swoqaeiwxombppeieindumruvxmi6wa4wel3nibm"><p lang="en">New profile picture~

#trans #queerArt #DigitalArt #krita #MadeWithKrita #Sketch #Anime<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lio44ccbm22m?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lio44ccbm22m?ref_src=embed">20 February 2025 at 23:46</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lc3xoo5c5c2z" data-bluesky-cid="bafyreidwinklhtleamaibmtagcqpsr6jvvjmdmvmusnrln545n3kc2g7h4"><p lang="en">friendly reminder that if I&#x27;m losing an argument to you online that this is who you are bullying~

#QueerArt #DigitalArt #Trans #MadeWithKrita #Krita #Anime #Manga<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lc3xoo5c5c2z?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lc3xoo5c5c2z?ref_src=embed">November 29, 2024 at 4:08 PM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lbo4wkvt6k2j" data-bluesky-cid="bafyreicjvxp4vrcup3olpialhzexq2gt2bpodw37o5toqaeks75hkmozai"><p lang="en">sketch~<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lbo4wkvt6k2j?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lbo4wkvt6k2j?ref_src=embed">November 24, 2024 at 4:05 AM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lbmqqqytbc2s" data-bluesky-cid="bafyreib43y3gamaypq4m5346ymahacmdeqj6tws4eqibdrlcubknj23dlu"><p lang="en">Disclaimer: haven&#x27;t watched many victorian dramas (except I guess like villainess isekai mangas ig but idk if they count)

#trans #QueerArt<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lbmqqqytbc2s?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lbmqqqytbc2s?ref_src=embed">November 23, 2024 at 2:54 PM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lbm2lmqk7s2j" data-bluesky-cid="bafyreiczdxekmz25nry7jtxju2gkcoff54owtovgz22o5k542hxyg3tbxq"><p lang="en">sketch~<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lbm2lmqk7s2j?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lbm2lmqk7s2j?ref_src=embed">November 23, 2024 at 8:18 AM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export


#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lb2omf7j2c2c" data-bluesky-cid="bafyreih2bsfi7qkut5cb7yiac6zrkpyc7ve56x6jaxq6tv3pkg43kex3oq"><p lang="en">BNHA True Ending~

#Trans #DigitalArt #Anime #BokuNoHero #TransfemMidoriya #MidoriyaXBakugo #Art #Manga #WebComic #QueerArt #BokuNoHeroAcademia #MyHeroAcademia #MidoriyaIzuku<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lb2omf7j2c2c?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lb2omf7j2c2c?ref_src=embed">November 16, 2024 at 10:28 AM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lajre6eiik2n" data-bluesky-cid="bafyreicmfogonidimnzmjlbsllzfctsiqeees6ykt7ax4gbgbsqcez2amm"><p lang="en">&quot;would you like a hug?&quot;

me:

#trans #trans_artist #queerArt #DigitalArt #Krita #Anime #Manga #Sketch #JJBA #JojosBizzareAdventure<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lajre6eiik2n?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lajre6eiik2n?ref_src=embed">November 9, 2024 at 5:02 PM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export


#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3laix3kwbak2n" data-bluesky-cid="bafyreia4muunj3jimdllg2byi5ufdmswwpmi2sef23gje7jr2ewnq25yam"><p lang="en">transfems only want one thing and it&#x27;s fucking disgustinggg!!!!!!<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3laix3kwbak2n?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3laix3kwbak2n?ref_src=embed">November 9, 2024 at 9:12 AM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3lah3zcebpe2p" data-bluesky-cid="bafyreifa5lgavfnyxuquhaahzgy32dkhjuikcodz2kjy5wn2p6kttbdwri"><p lang="en">mood~

#digitalArt #art #anime #manga #sketch #krita #trans #transArtist #queerArt #sketch<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lah3zcebpe2p?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3lah3zcebpe2p?ref_src=embed">November 8, 2024 at 3:35 PM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export


#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3labn7joyou2l" data-bluesky-cid="bafyreigy7shr4erejqmodpr7robdy6g3wey5iueugw3dyebrnvji7jeepy"><p lang="en">In light of the recent #USpol events, how it currently feels as a dark skinned minority trans woman immigrating to the US next month...<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3labn7joyou2l?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3labn7joyou2l?ref_src=embed">November 6, 2024 at 11:26 AM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export


#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3kqokozztl22g" data-bluesky-cid="bafyreihs4cxxbai2fr5zzknuzxligp7a2fq7utx2eekhep4feowrocbgw4"><p lang="en">Arrrrrr you are a pirate<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3kqokozztl22g?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3kqokozztl22g?ref_src=embed">April 22, 2024 at 12:03 AM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3kpis6ok3dh2c" data-bluesky-cid="bafyreiettgn62udksg4jx5ju5kt3td4k5tojcy6jby3pp45ezd2y6najri"><p lang="en">&quot;Ohoho... just one more thing sir&quot; - Femme Columbo, probably

#columbo #DigitalArt #genderSwap #Krita<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3kpis6ok3dh2c?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3kpis6ok3dh2c?ref_src=embed">April 6, 2024 at 11:36 PM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export


#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3ko5byrf7z72c" data-bluesky-cid="bafyreibra4xdvtlwoh2wnbkwrpoxqystk3zpq4hzaownfecc4abafkmzli"><p lang="en">Drew my favorite monkey man!!!
#DigitalArt #LupinTheThird #Krita #FanArt<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ko5byrf7z72c?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ko5byrf7z72c?ref_src=embed">March 20, 2024 at 4:21 PM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export


#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3ko2rjficu22c" data-bluesky-cid="bafyreiffzfntnnt7wt3j4w7xg54ctnrywrrsa4qsajiuuhiah4fg3fhkdy"><p lang="en">Arle Nadja and Carbuncle from Puyo Puyo

#DigitalArt #fanart #puyopuyo<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ko2rjficu22c?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ko2rjficu22c?ref_src=embed">March 19, 2024 at 4:21 PM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export

#+begin_export html
<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:i32jjsch6xqcguzsf2lgbfyu/app.bsky.feed.post/3ko2rdtc73h2g" data-bluesky-cid="bafyreidhva3zwq7uw3kfcv65dpmyzazjuhz3rx43sdvirxle7w5o2hgncq"><p lang="en">Drawing of Ron and Toto from Ron Kamonohashi&#x27;s Forbidden deductions.

#rontoto 4 ever, cutest detective couple #drawing #art<br><br><a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ko2rdtc73h2g?ref_src=embed">[image or embed]</a></p>&mdash; Kiran (She/Her) (<a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu?ref_src=embed">@kirancodes.me</a>) <a href="https://bsky.app/profile/did:plc:i32jjsch6xqcguzsf2lgbfyu/post/3ko2rdtc73h2g?ref_src=embed">March 19, 2024 at 4:18 PM</a></blockquote><script async src="https://embed.bsky.app/static/embed.js" charset="utf-8"></script>
#+end_export
@@html: </div>@@
